### ISSUE TITLE
L2R Lung CT testing

### ISSUE THREAD

**Issue by clarkbab** [uncbiag/uniGradICON#22]
Hi there,

I'm running the UniGradICON model on a [test dataset](https://zenodo.org/records/4048761#.X241gS-21AZ) of inhalation/exhalation paired lung CT images from the [Learn2Reg challenge 2021](https://learn2reg.grand-challenge.org/Learn2Reg2021/). I'm also comparing this against a [voxelmorph](https://github.com/voxelmorph/voxelmorph) model that I trained on the [training dataset](https://zenodo.org/records/3835682) from the same challenge.

I've run UniGradICON using both the command line and python interfaces; however, there doesn't seem to a great degree of similarity between moved and fixed images. At a glance, the voxelmorph moved image matches the fixed image more closely and seems to have attained the correct anterior/posterior translation. See the example below for "case_022" from the testing dataset:

Voxelmorph:
<img width="913" alt="Screen Shot 2024-09-12 at 4 37 18 pm" src="https://github.com/user-attachments/assets/9f1222c3-fa89-4ff1-aa2f-1fc3042780e7">

UniGradICON (without instance optimisation):
<img width="894" alt="Screen Shot 2024-09-12 at 4 37 32 pm" src="https://github.com/user-attachments/assets/e6e6d4f9-9059-479c-a4e5-0c8d99c1cbbf">

Is this possibly user error (e.g. missing preprocessing or something), or due to mismatch between training and testing data?

Thanks,
Brett

**Comment by lintian-a** [comment]
Hi @clarkbab ,

Thanks for your interest in uniGradICON!

I test the case_022 with the command line (w/o IO) and attach the result below. The registration inside of the lung looks reasonable. The unrealistic stretches on the top and bottom are due to different FOVs of the two images, which is expected but less desired. Solving the registration with different FOVs is on our wish list.

![image](https://github.com/user-attachments/assets/aa4a033e-13b7-4b1a-81e1-8f959e6739ae)

One thing I noticed is that the fixed image has the complete lung in my visualization. While in the visualization you posted, the fixed image does not have the entire lung. Did you run any preprocessing on the original image? And what is the intensity range for the input images when you use the command line?

**Comment by clarkbab** [comment]
Hi @lintian-a 

Thanks for your response! The problem was user error: I'd applied normalisation somewhere in the preprocessing pipeline. The range of image values was [0, 1] instead of HU, which is expected by your model.

The results look much better now:

<img width="920" alt="Screen Shot 2024-09-13 at 2 23 52 pm" src="https://github.com/user-attachments/assets/120cbcb6-fbb6-4163-88f0-b1eaa0049e6c">

We apply cropping to the fixed images (sup-inf direction) to minimise the "stretching" you mention from different FOVs.
